version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "S3GetPathFiles"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Bucket=\"example-bucket-2021\" BucketTarget=\"example-bucket-2021\""

